# Generated by Django 5.1.6 on 2025-02-20 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='prix',
            field=models.IntegerField(),
        ),
    ]
